import Head from "next/head";
import Image from "next/image";
import misterbloggy from "../public/misterbloggy.png";
import dancinglime from "../public/Dancinglime.png";
import dancingpurple from "../public/Dancingpurple.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>Mr Bloggy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex flex-col justify-center items-center my-20 lg:flex-row">
          <div>
            <Image src={misterbloggy} width={400} />
          </div>
          <div>
            <Image src={dancingpurple} width={600} />
          </div>
        </div>
      </main>
    </>
  );
}
